version: "3.8"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./config.toml:/root/.streamlit/config.toml
    restart: "unless-stopped"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=True
